# Generated by Django 4.2.3 on 2023-08-02 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_watchlist_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='highest_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bid', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
    ]
