# Generated by Django 4.2.3 on 2023-08-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='number_of_bids',
        ),
    ]
