# Generated by Django 4.2.3 on 2023-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_number_of_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='number_of_watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_watchlist',
            field=models.IntegerField(default=0),
        ),
    ]
