# Generated by Django 4.2.3 on 2023-08-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bidder', to='auctions.bid'),
        ),
    ]
