# Generated by Django 4.2.3 on 2023-08-14 14:18

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(default=auctions.models.Listing.imageDefault, max_length=500),
        ),
    ]
