# Generated by Django 4.2.3 on 2024-02-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
