# Generated by Django 4.2.3 on 2024-02-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='editable',
        ),
    ]
