# Generated by Django 4.2.3 on 2024-02-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
