# Generated by Django 4.2.3 on 2023-08-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_highest_bid_bid_highest_bidder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='listing_price',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bid', to='auctions.bid'),
        ),
    ]
