# Generated by Django 4.2.3 on 2023-08-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_bid_number_of_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='highest_bidder',
            new_name='bidder',
        ),
    ]
