# Generated by Django 4.2.3 on 2023-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_number_of_bids_alter_listing_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='number_of_watchlist',
            field=models.IntegerField(default=0),
        ),
    ]
