# Generated by Django 4.2.3 on 2023-08-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_listing_highest_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bidder',
        ),
    ]
